[B#14] Feat: E2E Tests and CI
akai-org/dodo pull request #4
Opened 2024-11-12 11:53 UTC by smazik02

- new Docker scripts to build the entire stack or just the backend for developing: Windows and Linux
- full E2E testing suite with scripts to create and teardown a test database Docker container
- Github CI action to test after every change of backend code (+ a framework to utilize for the frontend as well)
- Prettier and ESLint fully functional on both frontend and backend (+ npm scripts to both check and fix errors)
- query validation in event controller
- additional OpenAPI definitions
- event exception entity change + new migration, DTO adjustments
- bug fixes found by tests

2024-11-13 18:01 UTC, Aeri4a submitted a review, later dismissed

2024-11-13 18:01 UTC, Aeri4a commented on apps/backend/package.json
> +    "test:db:restart": "pnpm test:db:rm && pnpm test:db:up",
restart -> start

2024-11-13 18:01 UTC, Aeri4a commented on apps/backend/src/resource/event/event.service.ts
> +        }
catch if possible

2024-11-13 18:01 UTC, Aeri4a commented on apps/backend/src/resource/event/event.service.ts
> +        }
findOneByOrFail

2024-11-13 18:01 UTC, Aeri4a commented on apps/backend/src/resource/note/dto/note.dto.ts
>      createdAt?: Date;
verify

2024-11-13 20:24 UTC, smazik02 commented on apps/backend/src/resource/note/dto/note.dto.ts
>      createdAt?: Date;
A single NoteDTO is used as both a create and return DTO. CreatedAt date is generated automatically on INSERT and is not given as a parameter, so doesn't need to be validated. Maybe we should think about a separate Create and Return DTO though...

2024-11-13 21:27 UTC, Aeri4a approved these changes

2024-11-13 21:29 UTC, Aeri4a requested changes
two times tests

2024-11-14 19:03 UTC, m-olej commented on .github/workflows/backend-test.yml
Consider adding types: [event_type] to limit when the workflow should trigger 
And an **if** clause for specific jobs that checks if expected event triggered it
  
research this: https://github.com/orgs/community/discussions/26724

2024-11-14 22:00 UTC, Aeri4a approved these changes

2024-11-14 22:13 UTC, merged